# Generated by Django 3.1.7 on 2021-03-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(default='', max_length=30, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='user_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
